import type { ReviewReason } from "../scan/detect";
import type { ScanFailure } from "../scan/protocol";

const fr = {
  pages: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
  toCheck: (count: number) => (count === 1 ? "⚠ 1 page à vérifier" : `⚠ ${count} pages à vérifier`),
  stillToCheck: (count: number) => (count === 1 ? "1 page est encore à vérifier. Télécharger quand même ?" : `${count} pages sont encore à vérifier. Télécharger quand même ?`),
  addPhotos: "Ajouter des photos",
  downloadAll: "Tout télécharger",
  download: "Télécharger",
  rename: "Nom du document",
  removeDocument: "Supprimer le document",
  confirmRemove: (name: string, count: number) => `Supprimer « ${name} » et ses ${count} page(s) ? Vous pourrez l'annuler.`,
  removePage: "Supprimer la page",
  correct: "Corriger",
  newDocument: "Nouveau document",
  undo: "Annuler",
  redo: "Rétablir",
  waiting: "Préparation…",
  back: "Retour à la planche",
  next: "Page suivante",
  finish: "Terminer",
  corners: "Coins",
  eraser: "Gomme",
  eraserSize: "Taille de la gomme",
  rotate: "Pivoter d'un quart de tour",
  render: "Rendu",
  document: "Document",
  color: "Couleur",
  watermark: "Filigrane",
  watermarkAuto: (kept: boolean) => `Auto (${kept ? "gardé" : "retiré"})`,
  watermarkKeep: "Gardé",
  watermarkDrop: "Retiré",
  format: "Format",
  formats: { auto: "Auto", a4: "A4", a5: "A5", letter: "Lettre" },
  restoreAuto: "Rétablir la détection auto",
  photo: "Photo",
  result: "Résultat",
  updating: "Mise à jour de la page…",
  cornersHint: "Glissez les coins sur ceux de la page. Choisissez la gomme pour effacer autour.",
  eraserHint: "Passez la gomme sur ce qui doit devenir blanc.",
  crossed: "Ces coins se croisent : la page ne serait plus un quadrilatère.",
  manualCorners: "Coins posés à la main.",
  reasons: {
    noPageFound: "Aucune page trouvée : la photo entière est gardée.",
    unusualRatio: "Format inhabituel : vérifiez les coins.",
    weakEdge: "Un bord de la page est peu net.",
    cornerMoved: "Un coin est peut-être caché ou plié.",
  } satisfies Record<ReviewReason, string>,
  failures: {
    unsupported: "Ce fichier n'est pas une photo lisible (JPEG, PNG ou HEIC).",
    unreadable: "Cette photo n'a pas pu être lue.",
    renderFailed: "Cette page n'a pas pu être redressée.",
    engineUnavailable: "Le moteur du scanner n'a pas pu démarrer. Rechargez la page.",
  } satisfies Record<ScanFailure, string>,
  leave: "Des documents n'ont pas été téléchargés.",
  searchable: "Texte cherchable",
  reading: (count: number) => (count === 1 ? "Lecture d'une page…" : `Lecture de ${count} pages…`),
};

const en: typeof fr = {
  pages: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
  toCheck: (count: number) => (count === 1 ? "⚠ 1 page to check" : `⚠ ${count} pages to check`),
  stillToCheck: (count: number) => (count === 1 ? "1 page is still to check. Download anyway?" : `${count} pages are still to check. Download anyway?`),
  addPhotos: "Add photos",
  downloadAll: "Download all",
  download: "Download",
  rename: "Document name",
  removeDocument: "Remove the document",
  confirmRemove: (name: string, count: number) => `Remove “${name}” and its ${count} page(s)? You can undo it.`,
  removePage: "Remove the page",
  correct: "Correct",
  newDocument: "New document",
  undo: "Undo",
  redo: "Redo",
  waiting: "Preparing…",
  back: "Back to the board",
  next: "Next page",
  finish: "Done",
  corners: "Corners",
  eraser: "Eraser",
  eraserSize: "Eraser size",
  rotate: "Rotate a quarter turn",
  render: "Rendering",
  document: "Document",
  color: "Color",
  watermark: "Watermark",
  watermarkAuto: (kept: boolean) => `Auto (${kept ? "kept" : "removed"})`,
  watermarkKeep: "Kept",
  watermarkDrop: "Removed",
  format: "Size",
  formats: { auto: "Auto", a4: "A4", a5: "A5", letter: "Letter" },
  restoreAuto: "Restore automatic detection",
  photo: "Photo",
  result: "Result",
  updating: "Updating the page…",
  cornersHint: "Drag the corners onto the page's own. Choose the eraser to clean around it.",
  eraserHint: "Pass the eraser over what must turn white.",
  crossed: "These corners cross: the page would no longer be a quadrilateral.",
  manualCorners: "Corners set by hand.",
  reasons: {
    noPageFound: "No page found: the whole photo is kept.",
    unusualRatio: "Unusual shape: check the corners.",
    weakEdge: "One edge of the page is faint.",
    cornerMoved: "A corner may be hidden or folded.",
  },
  failures: {
    unsupported: "This file is not a readable photo (JPEG, PNG or HEIC).",
    unreadable: "This photo could not be read.",
    renderFailed: "This page could not be straightened.",
    engineUnavailable: "The scanner's engine could not start. Reload the page.",
  },
  leave: "Some documents were not downloaded.",
  searchable: "Searchable text",
  reading: (count: number) => (count === 1 ? "Reading one page…" : `Reading ${count} pages…`),
};

export const scannerTexts = { fr, en };
export type ScannerTexts = typeof fr;
