import type { ReviewReason } from "../scan/detect";
import type { ScanFailure } from "../scan/protocol";

const fr = {
  pages: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
  toCheck: (count: number) => (count === 1 ? "⚠ 1 page à vérifier" : `⚠ ${count} pages à vérifier`),
  stillToCheck: (count: number, saving: boolean) =>
    `${count === 1 ? "1 page est encore à vérifier." : `${count} pages sont encore à vérifier.`} ${saving ? "Enregistrer" : "Télécharger"} quand même ?`,
  addPhotos: "Ajouter des photos",
  downloadAll: "Tout télécharger",
  download: "Télécharger",
  saveAll: "Tout enregistrer…",
  save: "Enregistrer…",
  saveConfirm: "Enregistrer",
  saveFailed: "L'enregistrement a échoué :",
  cancel: "Annuler",
  remove: "Supprimer",
  rename: "Nom du document",
  removeDocument: "Supprimer le document",
  confirmRemove: (name: string, count: number) => `Supprimer « ${name} » et ses ${count} page(s) ? Vous pourrez l'annuler.`,
  removePage: "Supprimer la page",
  correct: "Corriger",
  newDocument: "Nouveau document",
  undo: "Annuler",
  redo: "Rétablir",
  waiting: "Préparation…",
  back: "Retour à la planche",
  next: "Page suivante",
  finish: "Terminer",
  corners: "Coins",
  eraser: "Gomme",
  eraserSize: "Taille de la gomme",
  rotate: "Pivoter d'un quart de tour",
  render: "Rendu",
  document: "Document",
  color: "Couleur",
  watermark: "Filigrane",
  watermarkAuto: (kept: boolean) => `Auto (${kept ? "gardé" : "retiré"})`,
  watermarkKeep: "Gardé",
  watermarkDrop: "Retiré",
  format: "Format",
  formats: { auto: "Auto", a4: "A4", a5: "A5", letter: "Lettre" },
  restoreAuto: "Rétablir la détection auto",
  photo: "Photo",
  result: "Résultat",
  updating: "Mise à jour de la page…",
  cornersHint: "Glissez les coins sur ceux de la page. Choisissez la gomme pour effacer autour.",
  eraserHint: "Passez la gomme sur ce qui doit devenir blanc.",
  crossed: "Ces coins se croisent : la page ne serait plus un quadrilatère.",
  manualCorners: "Coins posés à la main.",
  reasons: {
    noPageFound: "Aucune page trouvée : la photo entière est gardée.",
    unusualRatio: "Format inhabituel : vérifiez les coins.",
    weakEdge: "Un bord de la page est peu net.",
    cornerMoved: "Un coin est peut-être caché ou plié.",
  } satisfies Record<ReviewReason, string>,
  failures: {
    unsupported: "Ce fichier n'est pas une photo lisible (JPEG, PNG ou HEIC).",
    unreadable: "Cette photo n'a pas pu être lue.",
    renderFailed: "Cette page n'a pas pu être redressée.",
    engineUnavailable: "Le moteur du scanner n'a pas pu démarrer. Rechargez la page.",
  } satisfies Record<ScanFailure, string>,
  leave: "Des documents n'ont pas été téléchargés.",
  searchable: "Texte cherchable",
  reading: (count: number) => (count === 1 ? "Lecture d'une page…" : `Lecture de ${count} pages…`),
};

const en: typeof fr = {
  pages: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
  toCheck: (count: number) => (count === 1 ? "⚠ 1 page to check" : `⚠ ${count} pages to check`),
  stillToCheck: (count: number, saving: boolean) =>
    `${count === 1 ? "1 page is still to check." : `${count} pages are still to check.`} ${saving ? "Save" : "Download"} anyway?`,
  addPhotos: "Add photos",
  downloadAll: "Download all",
  download: "Download",
  saveAll: "Save all…",
  save: "Save…",
  saveConfirm: "Save",
  saveFailed: "Saving failed:",
  cancel: "Cancel",
  remove: "Remove",
  rename: "Document name",
  removeDocument: "Remove the document",
  confirmRemove: (name: string, count: number) => `Remove “${name}” and its ${count} page(s)? You can undo it.`,
  removePage: "Remove the page",
  correct: "Correct",
  newDocument: "New document",
  undo: "Undo",
  redo: "Redo",
  waiting: "Preparing…",
  back: "Back to the board",
  next: "Next page",
  finish: "Done",
  corners: "Corners",
  eraser: "Eraser",
  eraserSize: "Eraser size",
  rotate: "Rotate a quarter turn",
  render: "Rendering",
  document: "Document",
  color: "Color",
  watermark: "Watermark",
  watermarkAuto: (kept: boolean) => `Auto (${kept ? "kept" : "removed"})`,
  watermarkKeep: "Kept",
  watermarkDrop: "Removed",
  format: "Size",
  formats: { auto: "Auto", a4: "A4", a5: "A5", letter: "Letter" },
  restoreAuto: "Restore automatic detection",
  photo: "Photo",
  result: "Result",
  updating: "Updating the page…",
  cornersHint: "Drag the corners onto the page's own. Choose the eraser to clean around it.",
  eraserHint: "Pass the eraser over what must turn white.",
  crossed: "These corners cross: the page would no longer be a quadrilateral.",
  manualCorners: "Corners set by hand.",
  reasons: {
    noPageFound: "No page found: the whole photo is kept.",
    unusualRatio: "Unusual shape: check the corners.",
    weakEdge: "One edge of the page is faint.",
    cornerMoved: "A corner may be hidden or folded.",
  },
  failures: {
    unsupported: "This file is not a readable photo (JPEG, PNG or HEIC).",
    unreadable: "This photo could not be read.",
    renderFailed: "This page could not be straightened.",
    engineUnavailable: "The scanner's engine could not start. Reload the page.",
  },
  leave: "Some documents were not downloaded.",
  searchable: "Searchable text",
  reading: (count: number) => (count === 1 ? "Reading one page…" : `Reading ${count} pages…`),
};

const ptBR: typeof fr = {
  pages: (count: number) => (count === 1 ? "1 página" : `${count} páginas`),
  toCheck: (count: number) => (count === 1 ? "⚠ 1 página a verificar" : `⚠ ${count} páginas a verificar`),
  stillToCheck: (count: number, saving: boolean) =>
    `${count === 1 ? "1 página ainda precisa ser verificada." : `${count} páginas ainda precisam ser verificadas.`} ${saving ? "Salvar" : "Baixar"} mesmo assim?`,
  addPhotos: "Adicionar fotos",
  downloadAll: "Baixar tudo",
  download: "Baixar",
  saveAll: "Salvar tudo…",
  save: "Salvar…",
  saveConfirm: "Salvar",
  saveFailed: "Falha ao salvar:",
  cancel: "Cancelar",
  remove: "Excluir",
  rename: "Nome do documento",
  removeDocument: "Excluir o documento",
  confirmRemove: (name: string, count: number) => `Excluir “${name}” e suas ${count} página(s)? Você poderá desfazer.`,
  removePage: "Excluir a página",
  correct: "Corrigir",
  newDocument: "Novo documento",
  undo: "Desfazer",
  redo: "Refazer",
  waiting: "Preparando…",
  back: "Voltar à prancheta",
  next: "Próxima página",
  finish: "Concluir",
  corners: "Cantos",
  eraser: "Borracha",
  eraserSize: "Tamanho da borracha",
  rotate: "Girar um quarto de volta",
  render: "Renderização",
  document: "Documento",
  color: "Cor",
  watermark: "Marca d'água",
  watermarkAuto: (kept: boolean) => `Auto (${kept ? "mantida" : "removida"})`,
  watermarkKeep: "Mantida",
  watermarkDrop: "Removida",
  format: "Formato",
  formats: { auto: "Auto", a4: "A4", a5: "A5", letter: "Carta" },
  restoreAuto: "Restaurar a detecção automática",
  photo: "Foto",
  result: "Resultado",
  updating: "Atualizando a página…",
  cornersHint: "Arraste os cantos até os da página. Escolha a borracha para apagar em volta.",
  eraserHint: "Passe a borracha sobre o que deve ficar branco.",
  crossed: "Esses cantos se cruzam: a página deixaria de ser um quadrilátero.",
  manualCorners: "Cantos posicionados à mão.",
  reasons: {
    noPageFound: "Nenhuma página encontrada: a foto inteira é mantida.",
    unusualRatio: "Formato incomum: verifique os cantos.",
    weakEdge: "Uma borda da página está pouco nítida.",
    cornerMoved: "Um canto pode estar escondido ou dobrado.",
  },
  failures: {
    unsupported: "Este arquivo não é uma foto legível (JPEG, PNG ou HEIC).",
    unreadable: "Esta foto não pôde ser lida.",
    renderFailed: "Esta página não pôde ser endireitada.",
    engineUnavailable: "O mecanismo do scanner não pôde iniciar. Recarregue a página.",
  },
  leave: "Há documentos que não foram baixados.",
  searchable: "Texto pesquisável",
  reading: (count: number) => (count === 1 ? "Lendo uma página…" : `Lendo ${count} páginas…`),
};

export const scannerTexts = { fr, en, "pt-br": ptBR };
export type ScannerTexts = typeof fr;
