packages:
  - apps/*
allowBuilds:
  esbuild: true
  workerd: true
  sharp: true
  tesseract.js: false
minimumReleaseAgeExclude:
  - miniflare@5.20260926.1-alpha
  - wrangler@4.143.1
patchedDependencies:
  '@wasm-zoo/qpdf@0.1.1': patches/@wasm-zoo__qpdf@0.1.1.patch
