import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
import { readWithPdfjs } from "../engine/support";
import { chooseFiles, pdfFile, solidPng } from "./support";

for (const width of [1280, 390]) {
test(`rotates the page and freely rotates a signature while keeping zoomed dragging accurate at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  await page.goto("/en/sign-pdf");
  await chooseFiles(page, [await pdfFile("contract.pdf", ["One", "Two"])]);
  await expect(page.getByAltText("PDF page preview 1", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Import an image", exact: true }).click();
  await page.getByLabel("Choose a PNG, JPG or JPEG", { exact: true }).setInputFiles({ name: "signature.png", mimeType: "image/png", buffer: solidPng(120, 40, [90, 20, 150]) });
  await page.getByRole("button", { name: "Add to this page", exact: true }).click();
  await page.getByRole("button", { name: "Rotate the page 90°", exact: true }).click();
  const sheet = await page.locator(".signature-sheet").boundingBox();
  expect(sheet!.width).toBeGreaterThan(sheet!.height);
  await page.getByRole("button", { name: "Zoom in", exact: true }).click();
  const placement = page.locator(".signature-placement");
  await placement.getByRole("button", { name: "Signature", exact: true }).click();
  const handle = page.getByRole("button", { name: "Rotate the signature", exact: true });
  await handle.scrollIntoViewIfNeeded();
  const center = (await placement.boundingBox())!;
  const knob = (await handle.boundingBox())!;
  const cx = center.x + center.width / 2, cy = center.y + center.height / 2;
  const startX = knob.x + knob.width / 2, startY = knob.y + knob.height / 2;
  const angle = Math.atan2(startY - cy, startX - cx) + Math.PI / 4;
  const radius = Math.hypot(startX - cx, startY - cy);
  await page.mouse.move(startX, startY);
  await page.mouse.down();
  await page.mouse.move(cx + Math.cos(angle) * radius, cy + Math.sin(angle) * radius, { steps: 10 });
  await page.mouse.up();
  await expect(handle).toHaveAttribute("title", /45°$/);
  await handle.press("ArrowRight");
  await expect(handle).toHaveAttribute("title", /46°$/);
  await handle.press("Shift+ArrowLeft");
  await expect(handle).toHaveAttribute("title", /31°$/);
  const resize = page.getByRole("button", { name: "Resize the signature", exact: true });
  await resize.scrollIntoViewIfNeeded();
  const corners = () => placement.evaluate((element) => {
    const el = element as HTMLElement, sheet = el.closest(".signature-sheet")!;
    const rect = el.getBoundingClientRect();
    const matrix = new DOMMatrix(getComputedStyle(sheet).transform).multiply(new DOMMatrix(getComputedStyle(el).transform));
    const dx = matrix.a * el.offsetWidth / 2 + matrix.c * el.offsetHeight / 2;
    const dy = matrix.b * el.offsetWidth / 2 + matrix.d * el.offsetHeight / 2;
    return { x: rect.x + rect.width / 2 - dx, y: rect.y + rect.height / 2 - dy, dx: 2 * dx, dy: 2 * dy, width: parseFloat(el.style.width) };
  });
  const initial = await corners();
  const grip = (await resize.locator("span").boundingBox())!;
  expect(Math.abs(grip.x + grip.width / 2 - initial.x - initial.dx)).toBeLessThan(1.5);
  expect(Math.abs(grip.y + grip.height / 2 - initial.y - initial.dy)).toBeLessThan(1.5);
  await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2);
  await page.mouse.down();
  await page.mouse.move(grip.x + grip.width / 2 + initial.dx * 0.15, grip.y + grip.height / 2 + initial.dy * 0.15, { steps: 10 });
  await page.mouse.up();
  const resized = await corners();
  expect(resized.width / initial.width).toBeCloseTo(1.15, 1);
  expect(Math.abs(resized.x - initial.x)).toBeLessThan(1.5);
  expect(Math.abs(resized.y - initial.y)).toBeLessThan(1.5);
  await page.screenshot({ path: test.info().outputPath(`rotation-${width}.png`), animations: "disabled" });
  const move = placement.getByRole("button", { name: "Signature", exact: true });
  await move.focus();
  const before = (await placement.boundingBox())!;
  await move.press("ArrowRight");
  const after = (await placement.boundingBox())!;
  expect(after.x).toBeGreaterThan(before.x);
  expect(after.y).toBeCloseTo(before.y, 0);
  await page.getByRole("button", { name: "Next page", exact: true }).click();
  await page.getByRole("button", { name: "Rotate the page 90°", exact: true }).click();
  await page.getByRole("button", { name: "Rotate the page 90°", exact: true }).click();
  await page.getByRole("button", { name: "Sign the PDF", exact: true }).click();
  const pending = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download the PDF", exact: true }).click();
  const download = await pending;
  const output = new Uint8Array(await readFile((await download.path())!));
  expect((await readWithPdfjs(output)).map((p) => p.rotation)).toEqual([90, 180]);
});
}
