const en = {
  rotatePage: "Rotate the page 90°", rotateSignature: "Rotate the signature", moveSignature: "Move the signature",
  zoomIn: "Zoom in", zoomOut: "Zoom out", resetZoom: "Reset zoom to 100%",
  retry: "Retry preview",
  undoStroke: "Undo last stroke", enlargeDrawing: "Enlarge drawing area", closeDrawing: "Close drawing area", largeDrawLabel: "Draw your signature in the large area",
  drawingHelp: "Take your time. You can undo each stroke without starting over.", drawingLimit: "The drawing area is full. Undo a stroke, clear the drawing, or use this signature.",
  textMode: "Text", assets: "Too many different images. Remove unused signatures before adding another.",
  draw: "Draw", import: "Import an image", drawLabel: "Draw your signature", clear: "Clear the drawing", use: "Add to this page",
  choose: "Choose a PNG, JPG or JPEG", formats: "PNG/JPG/JPEG · up to 10 MB and 16 megapixels. PNG transparency is preserved; JPG keeps its background.",
  addHere: "Add here", placeHint: "Click the page, then Add here to choose the position.",
  add: "Add to this page", remove: "Remove this signature", size: "Signature size", previous: "Previous page", next: "Next page",
  page: "Page", of: "of", preview: "PDF page preview", loading: "Loading the page…", previewError: "This page could not be displayed.",
  placement: "Signature", resize: "Resize the signature", instructions: "Drag the signature to move it. Drag the corner to resize or ↻ to rotate. Click outside to preview. Hold Shift for 15° steps. Keyboard: arrow keys to move or rotate, + and - to resize.",
  loadingImage: "Preparing the image…", note: "A visual signature, without a digital certificate.",
  format: "Choose a valid PNG, JPG or JPEG file.", bytes: "This image exceeds 10 MB. Choose a smaller file.",
  pixels: "This image exceeds 16 megapixels. Reduce its dimensions first.", decode: "This image could not be read. Try another image.", empty: "Draw your signature first.",
};
const fr: typeof en = {
  rotatePage: "Pivoter la page de 90°", rotateSignature: "Pivoter la signature", moveSignature: "Déplacer la signature",
  zoomIn: "Zoom avant", zoomOut: "Zoom arrière", resetZoom: "Rétablir le zoom à 100 %",
  retry: "Réessayer l’aperçu",
  undoStroke: "Annuler le dernier trait", enlargeDrawing: "Agrandir la zone de dessin", closeDrawing: "Fermer la zone de dessin", largeDrawLabel: "Dessinez votre signature dans la grande zone",
  drawingHelp: "Prenez votre temps. Vous pouvez annuler chaque trait sans tout recommencer.", drawingLimit: "La zone de dessin est pleine. Annulez un trait, effacez le dessin ou utilisez cette signature.",
  textMode: "Texte", assets: "Trop d’images différentes. Retirez les signatures inutiles avant d’en ajouter une autre.",
  draw: "Dessiner", import: "Importer une image", drawLabel: "Dessinez votre signature", clear: "Effacer le dessin", use: "Ajouter sur cette page",
  choose: "Choisir un PNG, JPG ou JPEG", formats: "PNG/JPG/JPEG · 10 Mo et 16 mégapixels maximum. La transparence du PNG est conservée ; le JPG garde son fond.",
  addHere: "Ajouter ici", placeHint: "Cliquez sur la page, puis sur Ajouter ici pour choisir l’emplacement.",
  add: "Ajouter sur cette page", remove: "Retirer cette signature", size: "Taille de la signature", previous: "Page précédente", next: "Page suivante",
  page: "Page", of: "sur", preview: "Aperçu de la page PDF", loading: "Chargement de la page…", previewError: "Cette page n’a pas pu être affichée.",
  placement: "Signature", resize: "Redimensionner la signature", instructions: "Glissez la signature pour la déplacer, son coin pour la redimensionner ou ↻ pour la pivoter. Cliquez ailleurs pour voir l’aperçu. Maj : pas de 15°. Au clavier : les flèches pour déplacer ou pivoter, + et - pour redimensionner.",
  loadingImage: "Préparation de l’image…", note: "Une signature visuelle, sans certificat numérique.",
  format: "Choisissez un fichier PNG, JPG ou JPEG valide.", bytes: "Cette image dépasse 10 Mo. Choisissez un fichier plus léger.",
  pixels: "Cette image dépasse 16 mégapixels. Réduisez d’abord ses dimensions.", decode: "Cette image n’a pas pu être lue. Essayez une autre image.", empty: "Dessinez d’abord votre signature.",
};
export const signatureText = { en, fr };
